"""Multilingual phrase templates used to bootstrap the intent dataset.

The train-set is generated by filling ``{destination}`` with each node alias
across these templates in English, French, and Kinyarwanda. Combined with the
``augment`` helper (synonym replacement and token reordering) this produces
several thousand labelled phrases per facility.
"""
from __future__ import annotations

TEMPLATES_EN = [
    "I want to go to the {destination}",
    "I need to find {destination}",
    "Where is {destination}?",
    "Can you direct me to {destination}?",
    "Please take me to {destination}",
    "I am here to visit {destination}",
    "I have a meeting at {destination}",
    "{destination} please",
    "How do I get to {destination}?",
    "Show me the way to {destination}",
    "I am looking for {destination}",
    "I need directions to {destination}",
    "Help me reach {destination}",
    "{destination}",
]

TEMPLATES_FR = [
    "Je voudrais aller au {destination}",
    "Je cherche {destination}",
    "Où se trouve {destination} ?",
    "Pouvez-vous m'indiquer {destination} ?",
    "Emmenez-moi au {destination}",
    "Je suis ici pour voir {destination}",
    "J'ai rendez-vous au {destination}",
    "{destination} s'il vous plaît",
    "Comment aller au {destination} ?",
    "Montrez-moi le chemin vers {destination}",
    "Je dois rencontrer {destination}",
]

TEMPLATES_RW = [
    "Ndashaka kujya kuri {destination}",
    "Ndashaka kubona {destination}",
    "Nshaka gusura {destination}",
    "Mushobora kunyereka {destination}?",
    "{destination} iri he?",
    "Njyanye kuri {destination}",
    "Mfite inama muri {destination}",
    "Ndashaka guhura n'umuyobozi wa {destination}",
    "Ni hehe habarirwa {destination}?",
    "Nereke inzira yerekeza kuri {destination}",
]

SYNONYMS = {
    "office": ["office", "bureau", "ibiro"],
    "manager": ["manager", "head", "chief", "umuyobozi"],
    "department": ["department", "unit", "division", "ishami"],
    "room": ["room", "salle", "icyumba"],
    "meeting": ["meeting", "session", "inama"],
    "entrance": ["entrance", "gate", "lobby", "umuryango"],
}


def templates_for(language: str):
    language = (language or "en").lower()
    if language.startswith("fr"):
        return TEMPLATES_FR
    if language.startswith("rw") or language.startswith("kin"):
        return TEMPLATES_RW
    return TEMPLATES_EN
