/* eslint-disable react-refresh/only-export-components */
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';

const STORAGE_KEY = 'sinarms-language';
const SUPPORTED = ['en', 'fr', 'rw'];

const DICTIONARY = {
  en: {
    'lang.label': 'EN',
    'lang.english': 'English',
    'lang.french': 'Français',
    'lang.kinyarwanda': 'Kinyarwanda',

    'visitor.checkin.title': 'Welcome to {org}',
    'visitor.checkin.subtitle': 'Please check in to start your visit.',
    'visitor.checkin.location': 'Location',
    'visitor.checkin.fullName': 'Full Name',
    'visitor.checkin.idOrPhone': 'ID or Phone',
    'visitor.checkin.dest': 'Where are you going?',
    'visitor.checkin.destPlaceholder': 'e.g. Finance Office, HR Manager',
    'visitor.checkin.selectDest': 'Select a destination...',
    'visitor.checkin.other': 'Other (type it)',
    'visitor.checkin.start': 'Start Navigation',
    'visitor.checkin.analyzing': 'Analyzing destination...',
    'visitor.checkin.loading': 'System is still loading locations. Please try again.',
    'visitor.checkin.notFound': 'We could not find that destination. Please describe it differently.',
    'visitor.checkin.unable': 'Unable to start navigation right now.',
    'visitor.checkin.qrLoading': 'Preparing your QR check-in...',
    'visitor.checkin.qrFailed': 'Could not start your QR check-in. Please try again.',
    'visitor.checkin.idOrPhoneHint': 'Phone (e.g. 0788123456) or 16-digit National ID',
    'visitor.checkin.errors.nameRequired': 'Please enter your full name.',
    'visitor.checkin.errors.nameTooShort': 'Name must be at least 2 characters.',
    'visitor.checkin.errors.nameInvalid': 'Use letters, spaces, hyphens or apostrophes only.',
    'visitor.checkin.errors.idOrPhoneRequired': 'Phone number or National ID is required.',
    'visitor.checkin.errors.phoneInvalid': 'Enter a valid phone (07XXXXXXXX or +2507XXXXXXXX).',
    'visitor.checkin.errors.idInvalid': 'National ID must be exactly 16 digits.',
    'visitor.checkin.errors.idOrPhoneInvalid': 'Enter a valid phone (07XXXXXXXX) or 16-digit National ID.',

    'visitor.nav.routeInstructions': 'Route Instructions',
    'visitor.nav.endVisit': 'End Visit',
    'visitor.nav.progress': 'Progress',
    'visitor.nav.eta': 'ETA',
    'visitor.nav.min': 'min',
    'visitor.nav.destination': 'Destination',
    'visitor.nav.visitor': 'Visitor',
    'visitor.nav.youAreHere': 'You are here',
    'visitor.nav.metersAway': '{meters}m away',
    'visitor.nav.metersOf': '{done} of {total} meters',
    'visitor.nav.totalSteps': '{steps} step{plural} • {meters}m total',
    'visitor.nav.noRoute': 'No route instructions available. Please ask at the Reception desk.',
    'visitor.nav.recenter': 'Recenter map',
    'visitor.nav.focusRoute': 'Focus route',
    'visitor.nav.askAssistant': 'Ask assistant',
    'visitor.nav.alerts': 'Alerts & info',
    'visitor.nav.simStart': 'Simulate walking the route (demo)',
    'visitor.nav.simStop': 'Stop simulated walk',
    'visitor.nav.followSignage': 'Follow posted signage',
    'visitor.nav.scrollTop': 'Scroll to top',
    'visitor.nav.loading': 'Loading your route...',
    'visitor.nav.arrived.title': 'You have arrived',
    'visitor.nav.arrived.message': 'You reached {destination}.',
    'visitor.nav.arrived.spoken': 'You have reached your destination.',
    'visitor.nav.alerts.your': 'Your current visit',
    'visitor.nav.alerts.onSite': 'On site',
    'visitor.nav.alerts.remaining': '{meters}m remaining • ~{minutes} min',
    'visitor.nav.alerts.emergency': 'Emergency',
    'visitor.nav.alerts.emergencyText': 'If you feel unsafe or lost, contact Reception immediately.',
    'visitor.nav.alerts.callReception': 'Call Reception',

    'visitor.layout.online': 'Online',
    'visitor.layout.navigating': 'Navigating',

    'admin.users.assignedLocation': 'Assigned Location',
    'admin.users.selectLocation': 'Select a location...',

    'staff.login.title': 'Staff Console',
    'staff.login.subtitle': 'Sign in to manage the SINARMS facility network.',
    'staff.login.email': 'Email',
    'staff.login.password': 'Password',
    'staff.login.remember': 'Remember me',
    'staff.login.forgot': 'Forgot?',
    'staff.login.submit': 'Authenticate',
    'staff.login.failure': 'Unable to sign in.',

    'staff.layout.administrator': 'Administrator',
    'staff.layout.receptionist': 'Receptionist',
    'staff.layout.management': 'Management',
    'staff.layout.signOut': 'Sign Out',
    'staff.layout.workspace': 'Workspace',
    'staff.layout.controlCenter': 'SINARMS Control Center',
    'staff.layout.notifications': 'Notifications',
    'staff.layout.profile': 'Profile Details',

    'staff.nav.dashboard': 'Live Dashboard',
    'staff.nav.history': 'Visitor History',
    'staff.nav.organizations': 'Organizations',
    'staff.nav.analytics': 'Analytics',
    'staff.nav.users': 'Users & Roles',
    'staff.nav.faq': 'FAQ Database',
    'staff.nav.audit': 'Audit Log',

    'staff.history.title': 'Visitor History',
    'staff.history.subtitle': 'Complete record of past and current visitor sessions',
    'staff.history.refresh': 'Refresh',
    'staff.history.export': 'Export CSV',
    'staff.history.loadFailed': 'Failed to load visitor history.',
    'staff.history.totalVisits': 'Total Visits',
    'staff.history.active': 'Active',
    'staff.history.exited': 'Exited',
    'staff.history.avgDuration': 'Avg Duration',
    'staff.history.searchPlaceholder': 'Search by name, phone, email, destination…',
    'staff.history.range.today': 'Today',
    'staff.history.range.7d': 'Last 7 days',
    'staff.history.range.30d': 'Last 30 days',
    'staff.history.range.all': 'All time',
    'staff.history.status.all': 'All statuses',
    'staff.history.status.active': 'Active',
    'staff.history.status.exited': 'Exited',
    'staff.history.status.unknown': 'unknown',
    'staff.history.col.visitor': 'Visitor',
    'staff.history.col.destination': 'Destination',
    'staff.history.col.location': 'Location',
    'staff.history.col.checkin': 'Check-in',
    'staff.history.col.checkout': 'Check-out',
    'staff.history.col.duration': 'Duration',
    'staff.history.col.status': 'Status',
    'staff.history.loading': 'Loading visitor history…',
    'staff.history.empty.title': 'No visitors found',
    'staff.history.empty.subtitle': 'Try adjusting your filters or date range.',
    'staff.history.unknownVisitor': 'Unknown',
    'staff.history.showingCount': 'Showing {filtered} of {total} visitors',
    'staff.history.detail.unknownTitle': 'Unknown Visitor',
    'staff.history.detail.phone': 'Phone',
    'staff.history.detail.email': 'Email',
    'staff.history.detail.organization': 'Organization',
    'staff.history.detail.location': 'Location',
    'staff.history.detail.destination': 'Destination',
    'staff.history.detail.checkedIn': 'Checked in',
    'staff.history.detail.checkedOut': 'Checked out',
    'staff.history.detail.duration': 'Duration',
    'staff.history.detail.stillOnSite': 'Still on premises',
    'staff.history.detail.purpose': 'Purpose',
    'staff.history.detail.minutes': '{n} minutes',

    'staff.dashboard.title': 'Live Operations',
    'staff.dashboard.subtitle': '{location} • Active Shift • Real-time visitor tracking',
    'staff.dashboard.fallbackLocation': 'Head Office',
    'staff.dashboard.liveSync': 'Live Sync',
    'staff.dashboard.manualRegister': 'Manual Registration',
    'staff.dashboard.stat.activeVisitors': 'Active Visitors',
    'staff.dashboard.stat.totalToday': 'Total Today',
    'staff.dashboard.stat.activeAlerts': 'Active Alerts',
    'staff.dashboard.stat.avgDuration': 'Avg Duration',
    'staff.dashboard.tab.directory': 'Directory',
    'staff.dashboard.tab.liveMap': 'Live Map',
    'staff.dashboard.searchPlaceholder': 'Search visitors...',
    'staff.dashboard.col.visitor': 'Visitor',
    'staff.dashboard.col.destination': 'Destination',
    'staff.dashboard.col.currentZone': 'Current Zone',
    'staff.dashboard.col.duration': 'Duration',
    'staff.dashboard.col.actions': 'Actions',
    'staff.dashboard.checkout': 'Check-Out',
    'staff.dashboard.minutesShort': '{n} min',
    'staff.dashboard.minutesAgo': '{n}m ago',
    'staff.dashboard.hoursAgo': '{n}h ago',
    'staff.dashboard.popup.destination': 'Destination',
    'staff.dashboard.alerts.title': 'Security Alerts',
    'staff.dashboard.alerts.empty': 'No active alerts',
    'staff.dashboard.overview.title': 'Today\'s Overview',
    'staff.dashboard.overview.totalVisitors': 'Total Visitors',
    'staff.dashboard.overview.avgDuration': 'Avg Duration',
    'staff.dashboard.overview.onSite': 'Currently On-Site',
    'staff.dashboard.modal.title': 'Register Visitor',
    'staff.dashboard.modal.name': 'Full Name',
    'staff.dashboard.modal.namePlaceholder': 'Visitor Name',
    'staff.dashboard.modal.idOrPhone': 'ID or Phone',
    'staff.dashboard.modal.idOrPhonePlaceholder': 'ID number or phone',
    'staff.dashboard.modal.destination': 'Destination',
    'staff.dashboard.modal.destinationPlaceholder': 'Select destination...',
    'staff.dashboard.modal.host': 'Host Name (Optional)',
    'staff.dashboard.modal.hostPlaceholder': 'Whom are they visiting?',
    'staff.dashboard.modal.cancel': 'Cancel',
    'staff.dashboard.modal.confirm': 'Confirm Registration',
    'staff.dashboard.errors.noLocation': 'Your account is not assigned to a location.',
    'staff.dashboard.errors.required': 'Please provide the visitor name and destination.',
    'staff.dashboard.errors.checkout': 'Unable to check out visitor.',
    'staff.dashboard.errors.acknowledge': 'Unable to acknowledge alert.',
    'staff.dashboard.errors.register': 'Unable to register visitor.',

    'staff.adminOnly': 'Admin Only',
    'staff.faq.title': 'FAQ Database',
    'staff.faq.subtitle': 'Chatbot intelligence powered by MiniLM-L6-v2',
    'staff.faq.add': 'Add FAQ Entry',
    'staff.faq.entries': '{n} Entries',
    'staff.faq.searchPlaceholder': 'Search questions...',
    'staff.faq.matches': 'Matches',
    'staff.faq.deleteFailed': 'Unable to delete FAQ entry.',
    'staff.faq.modal.editTitle': 'Edit FAQ Entry',
    'staff.faq.modal.newTitle': 'New FAQ Entry',
    'staff.faq.modal.language': 'Language',
    'staff.faq.modal.langEn': 'English',
    'staff.faq.modal.langFr': 'French',
    'staff.faq.modal.langRw': 'Kinyarwanda',
    'staff.faq.modal.question': 'Question Variation',
    'staff.faq.modal.questionPlaceholder': 'e.g. Where can I find the canteen?',
    'staff.faq.modal.answer': 'Chatbot Answer',
    'staff.faq.modal.answerPlaceholder': 'Type the precise answer here...',
    'staff.faq.modal.cancel': 'Cancel',
    'staff.faq.modal.update': 'Update Entry',
    'staff.faq.modal.save': 'Save & Refresh Model',
    'staff.faq.modal.required': 'Question and answer are required.',
    'staff.faq.modal.saveFailed': 'Unable to save FAQ entry.',

    'landing.brand.tagline': 'Smart Navigation',
    'landing.nav.showcase': 'Showcase',
    'landing.nav.features': 'Features',
    'landing.nav.getStarted': 'Get Started',
    'landing.nav.staffLogin': 'Staff Login',
    'landing.nav.visitorPortal': 'Visitor Portal',

    'landing.hero.statusOnline': 'System Online V1.0',
    'landing.hero.titleA': 'Smart Facility',
    'landing.hero.titleB': 'Intelligence',
    'landing.hero.description': 'Welcome to the Smart Institutional Navigation and Resource Mapping System (SINARMS). The definitive solution for enterprise-grade visitor tracking, dynamic wayfinding, and real-time facility mapping.',
    'landing.hero.visitorCardTitle': 'Visitor Portal',
    'landing.hero.visitorCardDesc': 'Self-service check-in, AI assistance, and interactive indoor routing.',
    'landing.hero.visitorCardCta': 'Start Visit',
    'landing.hero.staffCardTitle': 'Staff Portal',
    'landing.hero.staffCardDesc': 'Real-time facility monitoring, layout editing, and analytics.',
    'landing.hero.staffCardCta': 'Staff Login',
    'landing.hero.liveTraffic': 'Live Traffic',
    'landing.hero.active': 'Active',
    'landing.hero.currentVisitors': 'Current Visitors',
    'landing.hero.checkedIn': '124 Checked In',
    'landing.hero.poweredBy': 'Powered by Ruliba Clays',

    'landing.showcase1.titleA': 'Elevate Your First',
    'landing.showcase1.titleB': 'Impression',
    'landing.showcase1.description': 'Transform your reception geometry into a state-of-the-art technological hub. Our smart mobile-first check-in flows and invisible geofencing checkpoints blend seamlessly into premium corporate environments.',
    'landing.showcase1.bullet1': 'Zero paper logs',
    'landing.showcase1.bullet2': 'VIP preregistration tracking',
    'landing.showcase1.bullet3': 'Instant host notifications',

    'landing.showcase2.titleA': 'Command Center',
    'landing.showcase2.titleB': 'Telemetry',
    'landing.showcase2.description': 'Empower your security and administrative teams with dark-mode optimized, high-density analytics dashboards. Monitor tracking anomalies and visitor flow in real-time across your entire physical estate.',
    'landing.showcase2.bullet1': 'Graph-based anomaly detection',
    'landing.showcase2.bullet2': 'Realtime heatmapping grids',
    'landing.showcase2.bullet3': 'Multi-facility synchronization',

    'landing.features.title': 'Enterprise-Grade Architecture',
    'landing.features.description': 'Engineered to handle high-traffic institutional environments. SINARMS provides a flawless, concurrent mapping and telemetry engine built for scale.',
    'landing.features.f1.title': 'Dynamic WebSockets',
    'landing.features.f1.desc': 'Real-time bipartite socket connections tracking live device geolocations with sub-second latency across the facility grid.',
    'landing.features.f2.title': 'MiniLM-L6-v2 AI',
    'landing.features.f2.desc': 'Native Natural Language Processing model deployed at the edge to instantly map visitor intent to the exact internal node coordinate.',
    'landing.features.f3.title': 'RBAC Security',
    'landing.features.f3.desc': 'Military-grade Role-Based Access Control enforcing deep permission layering between super-admins, receptionists, and active visitors.',
    'landing.features.f4.title': 'Graph-based Routing',
    'landing.features.f4.desc': 'Custom Dijkstra graph architecture navigating complex multidimensional floorplans over React-Leaflet GIS layers.',
    'landing.features.f5.title': 'Headless Scalability',
    'landing.features.f5.desc': 'Decoupled Vite/React rendering engine asynchronously feeding off a high-throughput Node/Python microservice backbone.',
    'landing.features.f6.title': '60fps Micro-interactions',
    'landing.features.f6.desc': 'Hardware-accelerated Framer Motion physics ensuring the interface feels entirely organic and physically present.',

    'landing.cta.titleA': 'Ready to map your',
    'landing.cta.titleB': 'world?',
    'landing.cta.description': 'Deploy SINARMS across your private infrastructure in under 15 minutes.',
    'landing.cta.staffBtn': 'Access Reception Console',
    'landing.cta.demoBtn': 'View Demo Run',

    'landing.footer.tagline': 'The Smart Institutional Navigation and Resource Mapping System. Engineered for enterprise-grade visitor tracking and dynamic indoor wayfinding.',
    'landing.footer.platform': 'Platform',
    'landing.footer.platform1': 'Visitor Management',
    'landing.footer.platform2': 'Indoor Navigation',
    'landing.footer.platform3': 'Telemetry Engine',
    'landing.footer.platform4': 'API Documentation',
    'landing.footer.company': 'Company',
    'landing.footer.company1': 'About Ruliba',
    'landing.footer.company2': 'Careers',
    'landing.footer.company3': 'Partner Network',
    'landing.footer.company4': 'System Status',
    'landing.footer.contact': 'Contact',
    'landing.footer.copyright': '© {year} SINARMS Technology. All rights reserved.',
    'landing.footer.privacy': 'Privacy',
    'landing.footer.terms': 'Terms',
    'landing.footer.cookies': 'Cookies',
  },

  fr: {
    'lang.label': 'FR',
    'lang.english': 'English',
    'lang.french': 'Français',
    'lang.kinyarwanda': 'Kinyarwanda',

    'visitor.checkin.title': 'Bienvenue à {org}',
    'visitor.checkin.subtitle': 'Veuillez vous enregistrer pour commencer.',
    'visitor.checkin.location': 'Lieu',
    'visitor.checkin.fullName': 'Nom complet',
    'visitor.checkin.idOrPhone': 'ID ou téléphone',
    'visitor.checkin.dest': 'Où allez-vous ?',
    'visitor.checkin.destPlaceholder': 'ex : Bureau des finances, DRH',
    'visitor.checkin.selectDest': 'Sélectionnez une destination...',
    'visitor.checkin.other': 'Autre (saisir)',
    'visitor.checkin.start': 'Démarrer la navigation',
    'visitor.checkin.analyzing': 'Analyse de la destination...',
    'visitor.checkin.loading': 'Chargement des lieux en cours. Réessayez.',
    'visitor.checkin.notFound': 'Destination introuvable. Décrivez-la différemment.',
    'visitor.checkin.unable': 'Impossible de démarrer la navigation pour le moment.',
    'visitor.checkin.qrLoading': 'Préparation de votre enregistrement QR...',
    'visitor.checkin.qrFailed': 'Impossible de démarrer l\'enregistrement QR. Réessayez.',
    'visitor.checkin.idOrPhoneHint': 'Téléphone (ex. 0788123456) ou pièce d\'identité (16 chiffres)',
    'visitor.checkin.errors.nameRequired': 'Veuillez saisir votre nom complet.',
    'visitor.checkin.errors.nameTooShort': 'Le nom doit comporter au moins 2 caractères.',
    'visitor.checkin.errors.nameInvalid': 'Utilisez uniquement des lettres, espaces, tirets ou apostrophes.',
    'visitor.checkin.errors.idOrPhoneRequired': 'Le numéro de téléphone ou la pièce d\'identité est requis.',
    'visitor.checkin.errors.phoneInvalid': 'Saisissez un téléphone valide (07XXXXXXXX ou +2507XXXXXXXX).',
    'visitor.checkin.errors.idInvalid': 'La pièce d\'identité doit comporter exactement 16 chiffres.',
    'visitor.checkin.errors.idOrPhoneInvalid': 'Saisissez un téléphone valide (07XXXXXXXX) ou une pièce d\'identité de 16 chiffres.',

    'visitor.nav.routeInstructions': 'Instructions de l\'itinéraire',
    'visitor.nav.endVisit': 'Terminer la visite',
    'visitor.nav.progress': 'Progrès',
    'visitor.nav.eta': 'ETA',
    'visitor.nav.min': 'min',
    'visitor.nav.destination': 'Destination',
    'visitor.nav.visitor': 'Visiteur',
    'visitor.nav.youAreHere': 'Vous êtes ici',
    'visitor.nav.metersAway': 'à {meters}m',
    'visitor.nav.metersOf': '{done} sur {total} mètres',
    'visitor.nav.totalSteps': '{steps} étape{plural} • {meters}m au total',
    'visitor.nav.noRoute': 'Aucune instruction disponible. Demandez à l\'accueil.',
    'visitor.nav.recenter': 'Recentrer la carte',
    'visitor.nav.focusRoute': 'Voir l\'itinéraire',
    'visitor.nav.askAssistant': 'Assistant',
    'visitor.nav.alerts': 'Alertes & infos',
    'visitor.nav.simStart': 'Simuler la marche (démo)',
    'visitor.nav.simStop': 'Arrêter la simulation',
    'visitor.nav.followSignage': 'Suivez la signalisation',
    'visitor.nav.scrollTop': 'Haut de la page',
    'visitor.nav.loading': 'Chargement de votre itinéraire...',
    'visitor.nav.arrived.title': 'Vous êtes arrivé',
    'visitor.nav.arrived.message': 'Vous avez atteint {destination}.',
    'visitor.nav.arrived.spoken': 'Vous êtes arrivé à destination.',
    'visitor.nav.alerts.your': 'Votre visite en cours',
    'visitor.nav.alerts.onSite': 'Sur place',
    'visitor.nav.alerts.remaining': 'reste {meters}m • ~{minutes} min',
    'visitor.nav.alerts.emergency': 'Urgence',
    'visitor.nav.alerts.emergencyText': 'En cas de problème, contactez l\'accueil immédiatement.',
    'visitor.nav.alerts.callReception': 'Appeler l\'accueil',

    'visitor.layout.online': 'En ligne',
    'visitor.layout.navigating': 'Navigation',

    'admin.users.assignedLocation': 'Lieu attribué',
    'admin.users.selectLocation': 'Sélectionnez un lieu...',

    'staff.login.title': 'Console Personnel',
    'staff.login.subtitle': 'Connectez-vous pour gérer le réseau SINARMS.',
    'staff.login.email': 'E-mail',
    'staff.login.password': 'Mot de passe',
    'staff.login.remember': 'Se souvenir de moi',
    'staff.login.forgot': 'Oublié ?',
    'staff.login.submit': 'Se connecter',
    'staff.login.failure': 'Connexion impossible.',

    'staff.layout.administrator': 'Administrateur',
    'staff.layout.receptionist': 'Réceptionniste',
    'staff.layout.management': 'Gestion',
    'staff.layout.signOut': 'Déconnexion',
    'staff.layout.workspace': 'Espace de travail',
    'staff.layout.controlCenter': 'Centre de contrôle SINARMS',
    'staff.layout.notifications': 'Notifications',
    'staff.layout.profile': 'Mon profil',

    'staff.nav.dashboard': 'Tableau de bord',
    'staff.nav.history': 'Historique des visiteurs',
    'staff.nav.organizations': 'Organisations',
    'staff.nav.analytics': 'Analytique',
    'staff.nav.users': 'Utilisateurs & rôles',
    'staff.nav.faq': 'Base FAQ',
    'staff.nav.audit': 'Journal d\'audit',

    'staff.history.title': 'Historique des visiteurs',
    'staff.history.subtitle': 'Registre complet des visites passées et en cours',
    'staff.history.refresh': 'Actualiser',
    'staff.history.export': 'Exporter en CSV',
    'staff.history.loadFailed': 'Échec du chargement de l\'historique.',
    'staff.history.totalVisits': 'Visites totales',
    'staff.history.active': 'Actifs',
    'staff.history.exited': 'Sortis',
    'staff.history.avgDuration': 'Durée moyenne',
    'staff.history.searchPlaceholder': 'Rechercher par nom, téléphone, e-mail, destination…',
    'staff.history.range.today': 'Aujourd\'hui',
    'staff.history.range.7d': '7 derniers jours',
    'staff.history.range.30d': '30 derniers jours',
    'staff.history.range.all': 'Tout',
    'staff.history.status.all': 'Tous les statuts',
    'staff.history.status.active': 'Actif',
    'staff.history.status.exited': 'Sorti',
    'staff.history.status.unknown': 'inconnu',
    'staff.history.col.visitor': 'Visiteur',
    'staff.history.col.destination': 'Destination',
    'staff.history.col.location': 'Lieu',
    'staff.history.col.checkin': 'Arrivée',
    'staff.history.col.checkout': 'Départ',
    'staff.history.col.duration': 'Durée',
    'staff.history.col.status': 'Statut',
    'staff.history.loading': 'Chargement de l\'historique…',
    'staff.history.empty.title': 'Aucun visiteur trouvé',
    'staff.history.empty.subtitle': 'Modifiez vos filtres ou la plage de dates.',
    'staff.history.unknownVisitor': 'Inconnu',
    'staff.history.showingCount': 'Affichage de {filtered} sur {total} visiteurs',
    'staff.history.detail.unknownTitle': 'Visiteur inconnu',
    'staff.history.detail.phone': 'Téléphone',
    'staff.history.detail.email': 'E-mail',
    'staff.history.detail.organization': 'Organisation',
    'staff.history.detail.location': 'Lieu',
    'staff.history.detail.destination': 'Destination',
    'staff.history.detail.checkedIn': 'Arrivée',
    'staff.history.detail.checkedOut': 'Départ',
    'staff.history.detail.duration': 'Durée',
    'staff.history.detail.stillOnSite': 'Toujours sur place',
    'staff.history.detail.purpose': 'Motif',
    'staff.history.detail.minutes': '{n} minutes',

    'staff.dashboard.title': 'Opérations en direct',
    'staff.dashboard.subtitle': '{location} • Service actif • Suivi des visiteurs en temps réel',
    'staff.dashboard.fallbackLocation': 'Siège',
    'staff.dashboard.liveSync': 'Sync en direct',
    'staff.dashboard.manualRegister': 'Enregistrement manuel',
    'staff.dashboard.stat.activeVisitors': 'Visiteurs actifs',
    'staff.dashboard.stat.totalToday': 'Total aujourd\'hui',
    'staff.dashboard.stat.activeAlerts': 'Alertes actives',
    'staff.dashboard.stat.avgDuration': 'Durée moyenne',
    'staff.dashboard.tab.directory': 'Annuaire',
    'staff.dashboard.tab.liveMap': 'Carte en direct',
    'staff.dashboard.searchPlaceholder': 'Rechercher des visiteurs...',
    'staff.dashboard.col.visitor': 'Visiteur',
    'staff.dashboard.col.destination': 'Destination',
    'staff.dashboard.col.currentZone': 'Zone actuelle',
    'staff.dashboard.col.duration': 'Durée',
    'staff.dashboard.col.actions': 'Actions',
    'staff.dashboard.checkout': 'Sortie',
    'staff.dashboard.minutesShort': '{n} min',
    'staff.dashboard.minutesAgo': 'il y a {n}m',
    'staff.dashboard.hoursAgo': 'il y a {n}h',
    'staff.dashboard.popup.destination': 'Destination',
    'staff.dashboard.alerts.title': 'Alertes de sécurité',
    'staff.dashboard.alerts.empty': 'Aucune alerte active',
    'staff.dashboard.overview.title': 'Aperçu du jour',
    'staff.dashboard.overview.totalVisitors': 'Visiteurs totaux',
    'staff.dashboard.overview.avgDuration': 'Durée moyenne',
    'staff.dashboard.overview.onSite': 'Sur place actuellement',
    'staff.dashboard.modal.title': 'Enregistrer un visiteur',
    'staff.dashboard.modal.name': 'Nom complet',
    'staff.dashboard.modal.namePlaceholder': 'Nom du visiteur',
    'staff.dashboard.modal.idOrPhone': 'Pièce d\'identité ou téléphone',
    'staff.dashboard.modal.idOrPhonePlaceholder': 'N° de pièce ou téléphone',
    'staff.dashboard.modal.destination': 'Destination',
    'staff.dashboard.modal.destinationPlaceholder': 'Sélectionnez une destination...',
    'staff.dashboard.modal.host': 'Nom de l\'hôte (facultatif)',
    'staff.dashboard.modal.hostPlaceholder': 'Qui visitent-ils ?',
    'staff.dashboard.modal.cancel': 'Annuler',
    'staff.dashboard.modal.confirm': 'Confirmer l\'enregistrement',
    'staff.dashboard.errors.noLocation': 'Votre compte n\'est pas affecté à un lieu.',
    'staff.dashboard.errors.required': 'Indiquez le nom et la destination du visiteur.',
    'staff.dashboard.errors.checkout': 'Impossible d\'enregistrer la sortie du visiteur.',
    'staff.dashboard.errors.acknowledge': 'Impossible d\'accuser réception de l\'alerte.',
    'staff.dashboard.errors.register': 'Impossible d\'enregistrer le visiteur.',

    'staff.adminOnly': 'Admin uniquement',
    'staff.faq.title': 'Base FAQ',
    'staff.faq.subtitle': 'Intelligence chatbot propulsée par MiniLM-L6-v2',
    'staff.faq.add': 'Ajouter une FAQ',
    'staff.faq.entries': '{n} entrées',
    'staff.faq.searchPlaceholder': 'Rechercher une question...',
    'staff.faq.matches': 'Correspondances',
    'staff.faq.deleteFailed': 'Impossible de supprimer la FAQ.',
    'staff.faq.modal.editTitle': 'Modifier la FAQ',
    'staff.faq.modal.newTitle': 'Nouvelle FAQ',
    'staff.faq.modal.language': 'Langue',
    'staff.faq.modal.langEn': 'Anglais',
    'staff.faq.modal.langFr': 'Français',
    'staff.faq.modal.langRw': 'Kinyarwanda',
    'staff.faq.modal.question': 'Variante de la question',
    'staff.faq.modal.questionPlaceholder': 'ex. Où se trouve la cantine ?',
    'staff.faq.modal.answer': 'Réponse du chatbot',
    'staff.faq.modal.answerPlaceholder': 'Saisissez la réponse exacte...',
    'staff.faq.modal.cancel': 'Annuler',
    'staff.faq.modal.update': 'Mettre à jour',
    'staff.faq.modal.save': 'Enregistrer & rafraîchir',
    'staff.faq.modal.required': 'Question et réponse obligatoires.',
    'staff.faq.modal.saveFailed': 'Impossible d\'enregistrer la FAQ.',

    'landing.brand.tagline': 'Navigation Intelligente',
    'landing.nav.showcase': 'Présentation',
    'landing.nav.features': 'Fonctionnalités',
    'landing.nav.getStarted': 'Démarrer',
    'landing.nav.staffLogin': 'Connexion Personnel',
    'landing.nav.visitorPortal': 'Portail Visiteur',

    'landing.hero.statusOnline': 'Système en ligne V1.0',
    'landing.hero.titleA': 'Intelligence',
    'landing.hero.titleB': 'des Sites',
    'landing.hero.description': 'Bienvenue sur SINARMS — la solution complète pour le suivi des visiteurs, l\'orientation dynamique et la cartographie en temps réel des sites.',
    'landing.hero.visitorCardTitle': 'Portail Visiteur',
    'landing.hero.visitorCardDesc': 'Enregistrement libre-service, assistance IA et orientation intérieure interactive.',
    'landing.hero.visitorCardCta': 'Commencer la visite',
    'landing.hero.staffCardTitle': 'Portail Personnel',
    'landing.hero.staffCardDesc': 'Suivi en temps réel, édition du plan et tableaux de bord analytiques.',
    'landing.hero.staffCardCta': 'Connexion Personnel',
    'landing.hero.liveTraffic': 'Trafic en direct',
    'landing.hero.active': 'Actif',
    'landing.hero.currentVisitors': 'Visiteurs actuels',
    'landing.hero.checkedIn': '124 enregistrés',
    'landing.hero.poweredBy': 'Propulsé par Ruliba Clays',

    'landing.showcase1.titleA': 'Soignez votre première',
    'landing.showcase1.titleB': 'impression',
    'landing.showcase1.description': 'Transformez votre accueil en pôle technologique de pointe. Nos parcours d\'enregistrement mobile et nos points de contrôle géolocalisés s\'intègrent naturellement aux environnements d\'entreprise haut de gamme.',
    'landing.showcase1.bullet1': 'Zéro registre papier',
    'landing.showcase1.bullet2': 'Pré-enregistrement VIP',
    'landing.showcase1.bullet3': 'Notifications hôte instantanées',

    'landing.showcase2.titleA': 'Centre de',
    'landing.showcase2.titleB': 'Pilotage',
    'landing.showcase2.description': 'Donnez à vos équipes de sécurité et d\'administration des tableaux de bord analytiques denses, optimisés mode sombre. Suivez les anomalies et les flux de visiteurs en temps réel sur tout votre patrimoine.',
    'landing.showcase2.bullet1': 'Détection d\'anomalies par graphes',
    'landing.showcase2.bullet2': 'Heatmaps temps réel',
    'landing.showcase2.bullet3': 'Synchronisation multi-sites',

    'landing.features.title': 'Architecture de niveau entreprise',
    'landing.features.description': 'Conçu pour les environnements à fort trafic. SINARMS fournit un moteur de cartographie et de télémétrie concurrent et fiable, prêt à l\'échelle.',
    'landing.features.f1.title': 'WebSockets dynamiques',
    'landing.features.f1.desc': 'Connexions socket temps réel suivant la géolocalisation des appareils avec une latence inférieure à la seconde.',
    'landing.features.f2.title': 'IA MiniLM-L6-v2',
    'landing.features.f2.desc': 'Modèle NLP déployé en local pour cartographier instantanément l\'intention du visiteur sur la coordonnée exacte du site.',
    'landing.features.f3.title': 'Sécurité RBAC',
    'landing.features.f3.desc': 'Contrôle d\'accès basé sur les rôles avec une stratification fine entre administrateurs, réceptionnistes et visiteurs.',
    'landing.features.f4.title': 'Routage par graphes',
    'landing.features.f4.desc': 'Architecture Dijkstra dédiée naviguant des plans multidimensionnels sur des couches GIS React-Leaflet.',
    'landing.features.f5.title': 'Évolutivité Headless',
    'landing.features.f5.desc': 'Moteur de rendu Vite/React découplé alimenté par une dorsale Node/Python à haut débit.',
    'landing.features.f6.title': 'Micro-interactions 60fps',
    'landing.features.f6.desc': 'Animations Framer Motion accélérées matériellement, pour une interface vivante et naturelle.',

    'landing.cta.titleA': 'Prêt à cartographier votre',
    'landing.cta.titleB': 'monde ?',
    'landing.cta.description': 'Déployez SINARMS sur votre infrastructure privée en moins de 15 minutes.',
    'landing.cta.staffBtn': 'Accéder à la console',
    'landing.cta.demoBtn': 'Voir la démo',

    'landing.footer.tagline': 'Le système intelligent de navigation et de cartographie institutionnelle. Conçu pour le suivi visiteur et l\'orientation intérieure dynamique.',
    'landing.footer.platform': 'Plateforme',
    'landing.footer.platform1': 'Gestion des visiteurs',
    'landing.footer.platform2': 'Navigation intérieure',
    'landing.footer.platform3': 'Moteur de télémétrie',
    'landing.footer.platform4': 'Documentation API',
    'landing.footer.company': 'Société',
    'landing.footer.company1': 'À propos de Ruliba',
    'landing.footer.company2': 'Carrières',
    'landing.footer.company3': 'Réseau partenaires',
    'landing.footer.company4': 'Statut système',
    'landing.footer.contact': 'Contact',
    'landing.footer.copyright': '© {year} SINARMS Technology. Tous droits réservés.',
    'landing.footer.privacy': 'Confidentialité',
    'landing.footer.terms': 'Conditions',
    'landing.footer.cookies': 'Cookies',
  },

  rw: {
    'lang.label': 'RW',
    'lang.english': 'English',
    'lang.french': 'Français',
    'lang.kinyarwanda': 'Kinyarwanda',

    'visitor.checkin.title': 'Ikaze muri {org}',
    'visitor.checkin.subtitle': 'Iyandikishe mbere yo kwinjira.',
    'visitor.checkin.location': 'Aho uri',
    'visitor.checkin.fullName': 'Amazina yose',
    'visitor.checkin.idOrPhone': 'Indangamuntu cyangwa Telefoni',
    'visitor.checkin.dest': 'Ugiye he?',
    'visitor.checkin.destPlaceholder': 'Urugero: Ibiro by\'imari, HR',
    'visitor.checkin.selectDest': 'Hitamo aho ugiye...',
    'visitor.checkin.other': 'Ikindi (andika)',
    'visitor.checkin.start': 'Tangira kwerekezwa',
    'visitor.checkin.analyzing': 'Turimo gusesengura aho ujya...',
    'visitor.checkin.loading': 'Sisitemu iracyatangira. Ongera ugerageze.',
    'visitor.checkin.notFound': 'Ntitwabashije kubona aho ugiye. Sobanura ukundi.',
    'visitor.checkin.unable': 'Ntitubashije gutangira kwerekezwa ubu.',
    'visitor.checkin.qrLoading': 'Turimo gutegura kwiyandikisha kwa QR...',
    'visitor.checkin.qrFailed': 'Ntitwabashije gutangira kwiyandikisha kwa QR. Ongera ugerageze.',
    'visitor.checkin.idOrPhoneHint': 'Telefoni (urugero: 0788123456) cyangwa indangamuntu (imibare 16)',
    'visitor.checkin.errors.nameRequired': 'Andika amazina yawe yose.',
    'visitor.checkin.errors.nameTooShort': 'Amazina agomba kuba afite nibura inyuguti 2.',
    'visitor.checkin.errors.nameInvalid': 'Koresha gusa inyuguti, imyanya, akabago cyangwa udushushondanga.',
    'visitor.checkin.errors.idOrPhoneRequired': 'Telefoni cyangwa indangamuntu birakenewe.',
    'visitor.checkin.errors.phoneInvalid': 'Andika telefoni nyayo (07XXXXXXXX cyangwa +2507XXXXXXXX).',
    'visitor.checkin.errors.idInvalid': 'Indangamuntu igomba kuba ifite imibare 16 gusa.',
    'visitor.checkin.errors.idOrPhoneInvalid': 'Andika telefoni nyayo (07XXXXXXXX) cyangwa indangamuntu y\'imibare 16.',

    'visitor.nav.routeInstructions': 'Amabwiriza y\'inzira',
    'visitor.nav.endVisit': 'Soza uruzinduko',
    'visitor.nav.progress': 'Aho ugeze',
    'visitor.nav.eta': 'Igihe gisigaye',
    'visitor.nav.min': 'min.',
    'visitor.nav.destination': 'Aho ugiye',
    'visitor.nav.visitor': 'Umushyitsi',
    'visitor.nav.youAreHere': 'Uri hano',
    'visitor.nav.metersAway': 'hasigaye m{meters}',
    'visitor.nav.metersOf': 'm{done} kuri m{total}',
    'visitor.nav.totalSteps': 'Intambwe {steps} • Hose m{meters}',
    'visitor.nav.noRoute': 'Nta nzira ihari. Baza ku biro by\'akira abashyitsi.',
    'visitor.nav.recenter': 'Subiza ikarita hagati',
    'visitor.nav.focusRoute': 'Reba inzira',
    'visitor.nav.askAssistant': 'Baza umufasha',
    'visitor.nav.alerts': 'Imenyesha n\'amakuru',
    'visitor.nav.simStart': 'Igana ko ugenda (demo)',
    'visitor.nav.simStop': 'Hagarika igana',
    'visitor.nav.followSignage': 'Kurikiza ibimenyetso',
    'visitor.nav.scrollTop': 'Garuka hejuru',
    'visitor.nav.loading': 'Turimo gutegura inzira yawe...',
    'visitor.nav.arrived.title': 'Wagereye',
    'visitor.nav.arrived.message': 'Wagereye kuri {destination}.',
    'visitor.nav.arrived.spoken': 'Wagereye aho wagiye.',
    'visitor.nav.alerts.your': 'Uruzinduko rwawe',
    'visitor.nav.alerts.onSite': 'Aho uri',
    'visitor.nav.alerts.remaining': 'hasigaye m{meters} • ~{minutes} min.',
    'visitor.nav.alerts.emergency': 'Ihutirwa',
    'visitor.nav.alerts.emergencyText': 'Niba utameze neza, hamagara ibiro by\'akira abashyitsi.',
    'visitor.nav.alerts.callReception': 'Hamagara ibiro',

    'visitor.layout.online': 'Kuri murandasi',
    'visitor.layout.navigating': 'Kuyobora',

    'admin.users.assignedLocation': 'Aho akorera',
    'admin.users.selectLocation': 'Hitamo aho akorera...',

    'staff.login.title': 'Konsole y\'abakozi',
    'staff.login.subtitle': 'Injira ucunge urusobe rwa SINARMS.',
    'staff.login.email': 'Imeyili',
    'staff.login.password': 'Ijambo ry\'ibanga',
    'staff.login.remember': 'Unyibuke',
    'staff.login.forgot': 'Wibagiwe?',
    'staff.login.submit': 'Injira',
    'staff.login.failure': 'Ntitwabashije kukwemeza.',

    'staff.layout.administrator': 'Umuyobozi',
    'staff.layout.receptionist': 'Ukira abashyitsi',
    'staff.layout.management': 'Imicungire',
    'staff.layout.signOut': 'Sohoka',
    'staff.layout.workspace': 'Ahakorerwa',
    'staff.layout.controlCenter': 'Ikigo cy\'igenzura cya SINARMS',
    'staff.layout.notifications': 'Imenyesha',
    'staff.layout.profile': 'Umwirondoro',

    'staff.nav.dashboard': 'Ikibaho cyo guhita',
    'staff.nav.history': 'Amateka y\'abashyitsi',
    'staff.nav.organizations': 'Imiryango',
    'staff.nav.analytics': 'Isesengura',
    'staff.nav.users': 'Abakoresha & inshingano',
    'staff.nav.faq': 'Ububiko bw\'ibibazo',
    'staff.nav.audit': 'Igitabo cy\'igenzura',

    'staff.history.title': 'Amateka y\'abashyitsi',
    'staff.history.subtitle': 'Inyandiko zuzuye z\'abashyitsi bashize n\'abari ku murongo',
    'staff.history.refresh': 'Ongera',
    'staff.history.export': 'Ohereza muri CSV',
    'staff.history.loadFailed': 'Byanze gusubira amakuru.',
    'staff.history.totalVisits': 'Ibyaranzwe byose',
    'staff.history.active': 'Bari hano',
    'staff.history.exited': 'Basohotse',
    'staff.history.avgDuration': 'Igihe cy\'impuzandengo',
    'staff.history.searchPlaceholder': 'Shakisha ku izina, telefoni, imeyili, aho ujya…',
    'staff.history.range.today': 'Uyu munsi',
    'staff.history.range.7d': 'Iminsi 7 ishize',
    'staff.history.range.30d': 'Iminsi 30 ishize',
    'staff.history.range.all': 'Igihe cyose',
    'staff.history.status.all': 'Ibyiciro byose',
    'staff.history.status.active': 'Ari hano',
    'staff.history.status.exited': 'Yasohotse',
    'staff.history.status.unknown': 'ntibizwi',
    'staff.history.col.visitor': 'Umushyitsi',
    'staff.history.col.destination': 'Aho ujya',
    'staff.history.col.location': 'Aho uri',
    'staff.history.col.checkin': 'Igihe yinjiye',
    'staff.history.col.checkout': 'Igihe yasohokeye',
    'staff.history.col.duration': 'Igihe',
    'staff.history.col.status': 'Imiterere',
    'staff.history.loading': 'Turimo gushaka amateka…',
    'staff.history.empty.title': 'Nta mushyitsi uboneka',
    'staff.history.empty.subtitle': 'Hindura amashakisho cyangwa igihe.',
    'staff.history.unknownVisitor': 'Ntibizwi',
    'staff.history.showingCount': 'Bigaragazwa {filtered} kuri {total} bashyitsi',
    'staff.history.detail.unknownTitle': 'Umushyitsi utazwi',
    'staff.history.detail.phone': 'Telefoni',
    'staff.history.detail.email': 'Imeyili',
    'staff.history.detail.organization': 'Umuryango',
    'staff.history.detail.location': 'Aho uri',
    'staff.history.detail.destination': 'Aho ujya',
    'staff.history.detail.checkedIn': 'Yinjiye',
    'staff.history.detail.checkedOut': 'Yasohotse',
    'staff.history.detail.duration': 'Igihe',
    'staff.history.detail.stillOnSite': 'Aracyari hano',
    'staff.history.detail.purpose': 'Impamvu',
    'staff.history.detail.minutes': 'iminota {n}',

    'staff.dashboard.title': 'Ibikorwa bigezweho',
    'staff.dashboard.subtitle': '{location} • Igihe gikora • Ikurikirana ry\'abashyitsi mu gihe nyacyo',
    'staff.dashboard.fallbackLocation': 'Ikicaro gikuru',
    'staff.dashboard.liveSync': 'Guhuza mu gihe nyacyo',
    'staff.dashboard.manualRegister': 'Iyandikisha ry\'intoki',
    'staff.dashboard.stat.activeVisitors': 'Abashyitsi bari hano',
    'staff.dashboard.stat.totalToday': 'Bose uyu munsi',
    'staff.dashboard.stat.activeAlerts': 'Imenyesha rikora',
    'staff.dashboard.stat.avgDuration': 'Igihe cy\'impuzandengo',
    'staff.dashboard.tab.directory': 'Urutonde',
    'staff.dashboard.tab.liveMap': 'Ikarita ikora',
    'staff.dashboard.searchPlaceholder': 'Shakisha abashyitsi...',
    'staff.dashboard.col.visitor': 'Umushyitsi',
    'staff.dashboard.col.destination': 'Aho ujya',
    'staff.dashboard.col.currentZone': 'Aho ari ubu',
    'staff.dashboard.col.duration': 'Igihe',
    'staff.dashboard.col.actions': 'Ibikorwa',
    'staff.dashboard.checkout': 'Sohoka',
    'staff.dashboard.minutesShort': 'iminota {n}',
    'staff.dashboard.minutesAgo': 'mbere y\'iminota {n}',
    'staff.dashboard.hoursAgo': 'mbere y\'amasaha {n}',
    'staff.dashboard.popup.destination': 'Aho ujya',
    'staff.dashboard.alerts.title': 'Imenyesha y\'umutekano',
    'staff.dashboard.alerts.empty': 'Nta menyesha rihari',
    'staff.dashboard.overview.title': 'Inyishu z\'umunsi',
    'staff.dashboard.overview.totalVisitors': 'Abashyitsi bose',
    'staff.dashboard.overview.avgDuration': 'Igihe cy\'impuzandengo',
    'staff.dashboard.overview.onSite': 'Bari aha ubu',
    'staff.dashboard.modal.title': 'Iyandikisha umushyitsi',
    'staff.dashboard.modal.name': 'Amazina yose',
    'staff.dashboard.modal.namePlaceholder': 'Izina ry\'umushyitsi',
    'staff.dashboard.modal.idOrPhone': 'Indangamuntu cyangwa Telefoni',
    'staff.dashboard.modal.idOrPhonePlaceholder': 'Nimero y\'indangamuntu cyangwa telefoni',
    'staff.dashboard.modal.destination': 'Aho ujya',
    'staff.dashboard.modal.destinationPlaceholder': 'Hitamo aho ujya...',
    'staff.dashboard.modal.host': 'Izina ry\'umuhuza (si itegeko)',
    'staff.dashboard.modal.hostPlaceholder': 'Bagiye gusura nde?',
    'staff.dashboard.modal.cancel': 'Hagarika',
    'staff.dashboard.modal.confirm': 'Emeza iyandikisha',
    'staff.dashboard.errors.noLocation': 'Konti yawe nta hantu yagenewe.',
    'staff.dashboard.errors.required': 'Andika izina n\'aho umushyitsi agiye.',
    'staff.dashboard.errors.checkout': 'Ntibyashobotse gusohora umushyitsi.',
    'staff.dashboard.errors.acknowledge': 'Ntibyashobotse kwemeza imenyesha.',
    'staff.dashboard.errors.register': 'Ntibyashobotse kwiyandikisha umushyitsi.',

    'staff.adminOnly': 'Umuyobozi gusa',
    'staff.faq.title': 'Ububiko bw\'ibibazo',
    'staff.faq.subtitle': 'Ubwenge bwa chatbot bushingiye kuri MiniLM-L6-v2',
    'staff.faq.add': 'Ongeraho ikibazo',
    'staff.faq.entries': '{n} biri muri ububiko',
    'staff.faq.searchPlaceholder': 'Shakisha ibibazo...',
    'staff.faq.matches': 'Bihuriye',
    'staff.faq.deleteFailed': 'Ntibyashobotse gusiba ikibazo.',
    'staff.faq.modal.editTitle': 'Hindura ikibazo',
    'staff.faq.modal.newTitle': 'Ikibazo gishya',
    'staff.faq.modal.language': 'Ururimi',
    'staff.faq.modal.langEn': 'Icyongereza',
    'staff.faq.modal.langFr': 'Igifaransa',
    'staff.faq.modal.langRw': 'Ikinyarwanda',
    'staff.faq.modal.question': 'Uburyo bw\'ikibazo',
    'staff.faq.modal.questionPlaceholder': 'urugero: Aho ndafata ifunguro?',
    'staff.faq.modal.answer': 'Igisubizo cya chatbot',
    'staff.faq.modal.answerPlaceholder': 'Andika igisubizo nyacyo hano...',
    'staff.faq.modal.cancel': 'Hagarika',
    'staff.faq.modal.update': 'Vugurura',
    'staff.faq.modal.save': 'Bika & ongera utangire',
    'staff.faq.modal.required': 'Ikibazo n\'igisubizo birakenewe.',
    'staff.faq.modal.saveFailed': 'Ntibyashobotse kubika ikibazo.',

    'landing.brand.tagline': 'Iyobora Riteye Imbere',
    'landing.nav.showcase': 'Ibyerekanwa',
    'landing.nav.features': 'Ibikubiyemo',
    'landing.nav.getStarted': 'Tangira',
    'landing.nav.staffLogin': 'Injira nk\'umukozi',
    'landing.nav.visitorPortal': 'Aho abashyitsi binjirira',

    'landing.hero.statusOnline': 'Sisitemu Ikora V1.0',
    'landing.hero.titleA': 'Ubwenge bw\'',
    'landing.hero.titleB': 'Ibikorwa',
    'landing.hero.description': 'Murakaza neza muri SINARMS — sisitemu yiyobora abashyitsi, ikabereka inzira mu nyubako kandi ikagenzura aho bari mu gihe nyacyo.',
    'landing.hero.visitorCardTitle': 'Aho abashyitsi binjirira',
    'landing.hero.visitorCardDesc': 'Kwiyandikisha wenyine, ubufasha bw\'ubwenge bw\'ubukorano, no kwerekezwa imbere.',
    'landing.hero.visitorCardCta': 'Tangira uruzinduko',
    'landing.hero.staffCardTitle': 'Aho abakozi binjirira',
    'landing.hero.staffCardDesc': 'Gukurikirana mu gihe nyacyo, guhindura ikarita, n\'isesengura.',
    'landing.hero.staffCardCta': 'Injira nk\'umukozi',
    'landing.hero.liveTraffic': 'Ibikorwa muri iki gihe',
    'landing.hero.active': 'Birakora',
    'landing.hero.currentVisitors': 'Abashyitsi bahari',
    'landing.hero.checkedIn': '124 banditse',
    'landing.hero.poweredBy': 'Itangwa na Ruliba Clays',

    'landing.showcase1.titleA': 'Tangiza neza',
    'landing.showcase1.titleB': 'umushyitsi',
    'landing.showcase1.description': 'Hindura icyumba cy\'akira abashyitsi mu kigo cy\'ikoranabuhanga rya none. Uburyo bwacu bwo kwiyandikisha kuri telefoni n\'amarembo y\'ubwenge bihuza n\'ibigo bikomeye.',
    'landing.showcase1.bullet1': 'Nta mpapuro zo kwandika',
    'landing.showcase1.bullet2': 'Kwiyandikisha kw\'abashyitsi b\'ingenzi',
    'landing.showcase1.bullet3': 'Imenyesha rikorewe icyarimwe',

    'landing.showcase2.titleA': 'Ikigo cy\'',
    'landing.showcase2.titleB': 'Igenzura',
    'landing.showcase2.description': 'Ha amakuru y\'ingenzi abakozi b\'umutekano n\'ubuyobozi. Kurikirana ibitameze neza n\'aho abashyitsi banyuze mu gihe nyacyo.',
    'landing.showcase2.bullet1': 'Kumenya ibitameze neza',
    'landing.showcase2.bullet2': 'Ibishushanyo by\'umuriro',
    'landing.showcase2.bullet3': 'Guhuza ahantu henshi',

    'landing.features.title': 'Imiterere y\'urwego rwo hejuru',
    'landing.features.description': 'Yashizweho gukoreshwa mu bigo bikora cyane. SINARMS itanga sisitemu y\'ikarita n\'igenzura ihamye, igendanwa neza.',
    'landing.features.f1.title': 'WebSockets zihinduka',
    'landing.features.f1.desc': 'Imihora ihora ihari ikurikirana ahantu hose mu gihe nyacyo.',
    'landing.features.f2.title': 'AI MiniLM-L6-v2',
    'landing.features.f2.desc': 'Igitekerezo cy\'umushyitsi gihita gihuzwa n\'aho ahari ako kanya.',
    'landing.features.f3.title': 'Umutekano RBAC',
    'landing.features.f3.desc': 'Ubucamanza bw\'inshingano bukomeye hagati y\'abayobozi, abakira abashyitsi n\'abashyitsi.',
    'landing.features.f4.title': 'Inzira ku rugendo',
    'landing.features.f4.desc': 'Imiterere ya Dijkstra inyura mu nyubako zigoye kuri ikarita ya React-Leaflet.',
    'landing.features.f5.title': 'Iyaguka idafite isura',
    'landing.features.f5.desc': 'Vite/React ihujwe na sisitemu y\'inyuma ya Node/Python.',
    'landing.features.f6.title': 'Imiyoboro ya 60fps',
    'landing.features.f6.desc': 'Animations za Framer Motion zikora vuba kandi neza.',

    'landing.cta.titleA': 'Witeguye gushushanya',
    'landing.cta.titleB': 'isi yawe?',
    'landing.cta.description': 'Shyira SINARMS mu kigo cyawe mu minota itarenze 15.',
    'landing.cta.staffBtn': 'Injira muri konsole',
    'landing.cta.demoBtn': 'Reba urugero',

    'landing.footer.tagline': 'Sisitemu y\'ubwenge yo kuyobora abashyitsi no gushushanya inyubako. Yashizweho gukurikirana abashyitsi no kubereka inzira.',
    'landing.footer.platform': 'Urubuga',
    'landing.footer.platform1': 'Gucunga abashyitsi',
    'landing.footer.platform2': 'Iyobora mu nyubako',
    'landing.footer.platform3': 'Sisitemu y\'igenzura',
    'landing.footer.platform4': 'Inyandiko za API',
    'landing.footer.company': 'Sosiyete',
    'landing.footer.company1': 'Ku byerekeye Ruliba',
    'landing.footer.company2': 'Akazi',
    'landing.footer.company3': 'Urusobe rw\'abafatanyabikorwa',
    'landing.footer.company4': 'Imimerere ya sisitemu',
    'landing.footer.contact': 'Twandikire',
    'landing.footer.copyright': '© {year} SINARMS Technology. Uburenganzira bwose.',
    'landing.footer.privacy': 'Ibanga',
    'landing.footer.terms': 'Amabwiriza',
    'landing.footer.cookies': 'Cookies',
  },
};

const LanguageContext = createContext(null);

function loadInitialLanguage() {
  try {
    const saved = window.localStorage.getItem(STORAGE_KEY);
    if (saved && SUPPORTED.includes(saved)) return saved;
  } catch {
    // ignore
  }
  return 'en';
}

function format(template, vars) {
  if (!template) return '';
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (_, key) => (vars[key] != null ? String(vars[key]) : ''));
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(loadInitialLanguage);

  useEffect(() => {
    try { window.localStorage.setItem(STORAGE_KEY, language); } catch { /* ignore */ }
  }, [language]);

  const setLanguage = useCallback((next) => {
    if (SUPPORTED.includes(next)) setLanguageState(next);
  }, []);

  const cycleLanguage = useCallback(() => {
    setLanguageState((current) => {
      const idx = SUPPORTED.indexOf(current);
      return SUPPORTED[(idx + 1) % SUPPORTED.length];
    });
  }, []);

  const t = useCallback(
    (key, vars) => {
      const dict = DICTIONARY[language] || DICTIONARY.en;
      const fallback = DICTIONARY.en[key];
      return format(dict[key] || fallback || key, vars);
    },
    [language],
  );

  const value = useMemo(
    () => ({
      language,
      languages: SUPPORTED,
      setLanguage,
      cycleLanguage,
      t,
      label: DICTIONARY[language]?.['lang.label'] || 'EN',
    }),
    [language, setLanguage, cycleLanguage, t],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
